algoritmo "semnome"
// Função :
// Autor :
// Data : 30/09/2021
// Seção de Declarações 
var
   Contador: inteiro
inicio
      Contador <- 15
      Enquanto (Contador >= 15) e (Contador <=200) faca
               Escreval ("============================================")
               Escreval ("O QUADRADO DE", Contador, " É: ", Contador ^2)
               Contador <- Contador + 1
      FimEnquanto
fimalgoritmo
