algoritmo "semnome"
// Função :
// Autor :
// Data : 27/09/2021
// Seção de Declarações 
var
   Valor, Contador, Salto: inteiro
inicio
      Contador <- 0
      Escreva ("Informe até onde você quer que o programa conte: ")
      Leia (Valor)
      Escreva ("Qual será o valor do salto? ")
      Leia (Salto)
      Enquanto (Contador <= Valor ) faca
               Escreval (Contador)
               Contador <- Contador + Salto
      FimEnquanto
      Escreva ("FIM DA CONTAGEM")
fimalgoritmo
