algoritmo "soma"
// Função :
// Autor :
// Data : 30/09/2021
// Seção de Declarações 
var
   Contador, SOMA: inteiro
inicio
      Contador <- 1
      SOMA <- 0
      Enquanto (Contador <= 10) faca
               Escreval (Contador)
               SOMA <- SOMA + Contador
               Contador <- Contador + 1

      FimEnquanto
      Escreva ("O RESULTADO DA SOMA DE TODOS OS NÚMERO É: ", SOMA)
fimalgoritmo

