algoritmo "potenciação"
// Função :
// Autor : Wesley
// Data : 04/10/2021
// Apresentar os resultados das potências de 3, variando do expoente 0 até o
// expoente 15. Deve ser considerado que qualquer número  elevado a zero é 1
// e elevado a 1 é ele msm.
var
   Contador: inteiro
inicio
      Contador <- 0
      Enquanto ( Contador <= 15) faca
               Escreval ("3^",Contador," = ", 3^Contador)
               Contador <- Contador + 1
      FimEnquanto
fimalgoritmo
