algoritmo "semnome"
// Função :
// Autor :
// Data : 16/09/2021
// Seção de Declarações 
var
   A, B, C, D, P, S, AB, CD: inteiro
inicio
      Escreva ("Informe o valor de A: ")
      Leia (A)
      Escreva ("Informe o valor de B: ")
      Leia (B)
      Escreva ("Informe o valor de C: ")
      Leia (C)
      Escreva ("Informe o valor de D: ")
      Leia (D)
      P <- A*C
      S <- C+D
      Escreva ("O produto AB é: ",P)
      Escreva (" A soma CD é: ",S)
fimalgoritmo
