algoritmo "semnome"
// Função :
// Autor :
// Data : 09/11/2021
// Seção de Declarações 
var
   N: inteiro
   Procedimento ParOuImpar (V: Inteiro)
   Inicio
         Se (V % 2 = 0) entao
            Escreval ("O número ", V, " é PAR")
         Senao
              Escreval ("O número ",V, " é  IMPAR")
         FimSe
   FimProcedimento
inicio
      Escreva ("Digite um número: ")
      Leia (N)
      ParOuImpar (N)
fimalgoritmo
