algoritmo "semnome"
// Função :
// Autor :
// Data : 30/09/2021
// Seção de Declarações 
var
   Contador, N: inteiro
inicio
      Contador <- 1
      Escreva ("INFORME QUAL A TABUADA VOCÊ QUER: ")
      Leia (N)
      Escreval ("----------------------------------------")
      Enquanto (Contador <= 10) faca
               Escreval (N, " X ", Contador, " = ", N*Contador)
               Contador <- Contador + 1
      FimEnquanto
fimalgoritmo
