algoritmo "semnome"
// Função :
// Autor :
// Data : 18/09/2021
// Seção de Declarações
var
D: real
inicio
      Escreva ("Informe quantidade de dinheiro: ")
      Leia (D)
      Se (D >=10000) entao
         Escreva ("Partiu Disney")

      Senao
         se (D >=5000) e (D<10000) entao
            Escreva ("Visitar a famili no inteior")
         Senao
            Escreva ("#chateado")
         Fimse
      Fimse
fimalgoritmo
