algoritmo "Potências de 3"
// Função : Esse programa deverá apresentar o resultado das potências de 3
// variando do expoente 0 ate o 15.
// Autor : Wesley
// Data : 06/11/2021
// Seção de Declarações 
var
   C: inteiro
inicio
      Escreval ("------------------------")
      Escreval ("     Potências de 3     ")
      Escreval ("------------------------")
      Para C de 0 ate 15 faca
           Escreval ("3 ^", C, " = ", 3^C)
      FimPara
fimalgoritmo
