algoritmo "semnome"
// Função :
// Autor :
// Data : 17/09/2021
// Seção de Declarações 
var
     Ano, Nasc, idade: inteiro
inicio
      Escreva ("Em que ano estamos: ")
      Leia (Ano)
      Escreva ("Em que ano você nasceu? ")
      Leia (Nasc)
      Idade <- Ano-Nasc
      Escreval ("Em", Ano, " Você tera", Idade, " Anos.")
      Se (idade >= 21) entao
      Escreva ("Você já tera atingido a maioridade.")
      fimse
fimalgoritmo
