algoritmo "semnome"
// Função :
// Autor :
// Data : 25/11/2021
// Seção de Declarações 
var
   V1, V2, S: inteiro
Funcao Soma (X, Y: inteiro): inteiro
var
inicio
      Retorne (X + Y)
FimFuncao
inicio
      Escreva ("Digite o primeiro valor: ")
      Leia (V1)
      Escreva ("Digite o segundo valor: ")
      Leia (V2)
      S <- Soma (V1, V2)
      Escreval ("A soma de ", V1, " + ", V2, " = ", S)
fimalgoritmo
