algoritmo "semnome"
// Função :
// Autor :
// Data : 30/09/2021
// Seção de Declarações 
var
   Contador, X, R: inteiro
inicio
      Contador <- 1
      Enquanto (Contador <= 5) faca
               Escreva ("DIGITE UM NÚMERO: ")
               Leia (X)
               R <- X*3
               Escreval ("O ", Contador, "o RESULTADO É:", R)
               Contador <- Contador + 1
      FimEnquanto
               
fimalgoritmo
